name: egovision
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - attrs
  - babel
  - backcall
  - beautifulsoup4
  - black
  - blas
  - bleach
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - coloredlogs
  - cryptography
  - cudatoolkit
  - cycler
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - ffmpeg
  - fftw
  - fontconfig
  - fonttools
  - freetype
  - giflib
  - glib
  - gmp
  - gnutls
  - gst-plugins-base
  - gstreamer
  - humanfriendly
  - icu
  - idna
  - importlib_metadata
  - importlib_resources
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libdeflate
  - libedit
  - libevent
  - libffi
  - libgcc
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libidn2
  - libllvm10
  - libopus
  - libpng
  - libpq
  - libsodium
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libuuid
  - libvpx
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libxslt
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - mypy_extensions
  - nb_conda
  - nb_conda_kernels
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - nettle
  - nodejs
  - notebook
  - nspr
  - nss
  - numexpr
  - numpy
  - numpy-base
  - openh264
  - openssl
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pathspec
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkgutil-resolve-name
  - platformdirs
  - ply
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - ptyprocess
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python_abi
  - pytorch
  - pytorch-mutex
  - pytz
  - pyzmq
  - qt-main
  - qt-webengine
  - qtconsole
  - qtpy
  - qtwebkit
  - readline
  - requests
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - sniffio
  - soupsieve
  - sqlite
  - terminado
  - testpath
  - threadpoolctl
  - tk
  - toml
  - tomli
  - torchaudio
  - torchvision
  - tornado
  - traitlets
  - typed-ast
  - typing-extensions
  - typing_extensions
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - x264
  - xz
  - zeromq
  - zlib
  - zstd
  - pip:
    - antlr4-python3-runtime
    - click
    - docker-pycreds
    - einops
    - filelock
    - gdown
    - gitdb
    - gitpython
    - huggingface-hub
    - importlib-metadata
    - kneed
    - omegaconf
    - pathtools
    - promise
    - protobuf
    - psutil
    - pyyaml
    - seaborn
    - sentry-sdk
    - setproctitle
    - shortuuid
    - smmap
    - timm
    - torchcam
    - tqdm
    - wandb
    - zipp
