
test
name: ???
shift: ActionNet-ActionNet
split: train
resume_from: ???
num_clips: 5
wandb_name: 'EMG_classification'

dataset:
  annotations_path: ../drive/MyDrive/train_val_EMG
  shift: ActionNet-ActionNet
  workers: 4
  stride: 2
  resolution: 224


models:
  EMG:
    model: EMG_classifier
    dropout: 0.2
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 10 
    epochs: 100
    lr: 1e-3
    sgd_momentum: 0.9
    weight_decay: 5e-3