action: train # train or test
name: ???
modality: ["EMG", "RGB"]
shift: S04-S04
split: train
resume_from: ???
num_clips: 5
wandb_name: 'Multimodal_classification'
in_features: 1024

dataset:
  annotations_path: ../drive/MyDrive/train_val_EMG
  shift: ActionNet-ActionNet
  workers: 4
  stride: 2
  resolution: 224
  EMG:
    features_name: translated/2023-06-10/features_lr0.001_b0.0001_2023-06-10 19:41:07.722501
  RGB:
    features_name: ACTIONNET/FT_D_S04_16f_5c


models:
  EMG:
    model: Unimodal_classifier
    dropout: 0.2
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 30 
    epochs: 100
    lr: 1e-2
    sgd_momentum: 0.9
    weight_decay: 5e-3
  RGB:
    model: Unimodal_classifier 
    dropout: 0.2
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 30 
    epochs: 100
    lr: 1e-2
    sgd_momentum: 0.9
    weight_decay: 5e-3