action: train # train or test
name: ???
split: train
resume_from: ???

dataset:
  annotations_path: ../drive/MyDrive/train_val_EMG
  shift: ActionNet-ActionNet
  workers: 4
  stride: 2
  resolution: 224


models:
  EMG:
    model: EMG_classifier
    dropout: 0.2
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 50 
    epochs: 100
    lr: 1e-6
    sgd_momentum: 0.9
    weight_decay: 5e-7