action: train # train or test
name: ???
shift: ActionNet-ActionNet
split: train
resume_from: ???
num_clips: 3
wandb_name: 'EMG_classification'
augmentation: False
embeddings_size: 512

dataset:
  annotations_path: train_val
  shift: ActionNet-ActionNet
  workers: 4
  stride: 2
  resolution: 224
train:
  num_iter: 300 # number of training iterations with total_batch size
  lr_steps: 50 # steps before reducing learning rate
  eval_freq: 50 # evaluation frequency
  num_clips: 3 # clips adopted in training
  dense_sampling: # sampling version adopted in training for each modality
    RGB: True
    EMG: True
  num_frames_per_clip: # number of frames adopted in training for each modality
    RGB: 16
    EMG: 64

models:
  EMG:
    model: EMG_classifier_parametric
    dropout: 0.2
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 80
    epochs: 10
    lr: 1e-2
    sgd_momentum: 0.9
    weight_decay: 5e-3