action: train # train or test
name: ???
shift: ActionNet-ActionNet
split: train
resume_from: ???
wandb_name: 'EMG_classification'
augmentation: False
embeddings_size: 1024

dataset:
  annotations_path: ../drive/MyDrive/train_val_EMG
  shift: ActionNet-ActionNet
  workers: 4
  stride: 2
  resolution: 224

models:
  EMG:
    model: EMG_classifier_parametric
    dropout: 0.2
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 40
    epochs: 5
    lr: 1e-2
    sgd_momentum: 0.9
    weight_decay: 5e-3