command:
  - /usr/local/envs/egovision/bin/python
  - train_classifier_EMG.py
  - action="train"
  - name="EMG_classification"
  - config=configs/classifier_emg.yaml
  - dataset.shift=ActionNet-ActionNet
  - train.num_iter=2500
  - models.RGB.lr=0.01
  - wandb_dir='Experiment_logs'
  - dataset.RGB.data_path=../ek_data/frames
method: random
metric:
  goal: minimize
  name: loss verb
parameters:
  lr:
    distribution: log_uniform
    max: 0.1
    min: 0.0001
  weight_decay:
    distribution: log_uniform
    max: 0.1
    min: 0.0001
program: aml22-ego/train_classifier_EMG.py
