program: /home/gabb/egovision_project/aml22-ego/train_VAE_features_clip.py
name: FC-VAE(rgb)
method: grid
metric:
  name: validation_loss
  goal: minimize
parameters:
  lr: 
    values: [0.0001, 0.00001]
command:
  - python
  - /home/gabb/egovision_project/aml22-ego/train_VAE_features_clip.py
  - action="train" 
  - name="VAE_FT_D_16f"
  - config=configs/VAE_save_feat.yaml   
  - dataset.shift=D1-D1
  - wandb_name='vae'
  - wandb_dir='Experiment_logs' 
  - dataset.RGB.data_path=../ek_data/frames    
  - dataset.RGB.features_name='EPIC/FT_D_D1_16f_5c'
  - models.RGB.model='VAE'
