action: save # train or test
name: ???
split: train
resume_from: ???
wandb_name: 'VAE_EMG'
last_model: 'saved_models/VAE_EMG/VAE_EMG_lr0.0001_b1e-05.pth'

train:
  bottleneck_size: 256
  EMG:
    feature_size: 1024
save:
  num_clips: 5
  dense_sampling:
    RGB: True
    EMG: True
  num_frames_per_clip:
    RGB: 16
    EMG: 32

dataset:
  annotations_path: train_val
  shift: ActionNet-ActionNet
  workers: 4
  stride: 2
  resolution: 224

models:
  EMG:
    model: VAE
    dropout: 0.2
    normalize: True
    kwargs: {}
    lr_steps: 30 
    epochs: 100
    lr: 1e-4
    lr_gamma: 0.1
    sgd_momentum: 0.9
    weight_decay: 1e-7
    beta: 0.00001
