action: save # train or test
name: ???
split: ???
resume_from: ???
wandb_name: 'VAE_EMG'

save:
  num_clips: 5
  dense_sampling:
    RGB: True
    EMG: True
  num_frames_per_clip:
    RGB: 16
    EMG: 16

dataset:
  annotations_path: ../drive/MyDrive/train_val_EMG
  shift: ActionNet-ActionNet
  workers: 4
  stride: 2
  resolution: 224

models:
  EMG:
    model: VAE
    dropout: 0.2
    normalize: True
    kwargs: {}
    lr_steps: 30 
    epochs: 100
    lr: 0.001
    lr_gamma: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7