action: save # train or test
name: ???
split: ???
resume_from: ???

save:
  num_clips: 5
  dense_sampling:
    RGB: True
  num_frames_per_clip:
    RGB: 16

dataset:
  annotations_path: train_val
  shift: ???
  workers: 4
  stride: 2
  resolution: 224
  RGB:
    data_path: ???
    tmpl: "img_{:010d}.jpg"
  Event:
    rgb4e: 6

models:
  RGB:
    architecture:
      bottleneck: 128
    model: VAE
    dropout: 0.2
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 30 
    epochs: 20
    lr: 0.001
    lr_gamma: 0.01
    beta: 0.00001


